# 端口
server:
  port: 9011


spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///my_cloud_shop
    username: root
    password: root
  # jpa配置
  jpa:
    show-sql: true
    database: mysql
    open-in-view: true
  # 应用名称
  application:
    name: shop-service-product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/ # 注册中心地址
#    registry-fetch-interval-seconds: 10 客户端拉取注册信息间隔时间，默认30s，第一次全量拉取，后面增量拉取
  instance:
    prefer-ip-address: true # 使用ip地址进行注册
    hostname: localhost # host
    lease-renewal-interval-in-seconds: 5 # 服务端心跳时间间隔，默认30s
    lease-expiration-duration-in-seconds: 10 # 服务器续约心跳到期时间默认90s
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 使用ip:port显示服务 spring.cloud.client.ip-address获取当前服务的ip