# 端口
server:
  port: 9002

# 应用名称
spring:
  application:
    name: shop-service-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/ #Eureka服务端地址
#      defaultZone: http://localhost:8080/eureka/,http://localhost:9090/eureka/ #Eureka服务端地址
  instance:
    prefer-ip-address: true # 使用ip进行注册
    hostname: localhost # 主机名

# 设置服务端负载均衡，默认轮询
SHOP-SERVICE-PRODUCT:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数